export { default as MyHeader } from './header/index'
export { default as MyFooter } from './footer/index'
export { default as MyLoader } from './loader/index'
export { default as MyAlert } from './alert/index'
export { default as MyModal } from './modal/index'
export { default as MyCard } from './card/index'
export { default as SlateEditor } from './editor/index'
